(* programs_md.wl : write PROGRAMS.md, the complete lists of the programs of the theorems
   (bounded: results/proof_many.json + data/verify_classes.wxf + data/verify_extra.wxf;
    unbounded: results/unbounded_certs/summary.json and the certificate files)
   usage: run.wl programs_md.wl <outfile> *)
outFile = $args[[2]];
pm = Import[FileNameJoin[{$repoDir, "results", "proof_many.json"}], "RawJSON"];
vc = Import[FileNameJoin[{$dataDir, "verify_classes.wxf"}]];
ve = Quiet[Check[Import[FileNameJoin[{$dataDir, "verify_extra.wxf"}]], <||>]];
cr = Import[FileNameJoin[{$repoDir, "results", "unbounded_certs", "certs_roots.json"}], "RawJSON"];   (* one record per certificate file (collect_cert_roots.py) *)
va = Quiet[Check[Import[FileNameJoin[{$dataDir, "verify_all.wxf"}]], <||>]];                       (* WL re-verification incl. period spectra *)
certFiles = FileNameTake /@ FileNames["*.json", FileNameJoin[{$repoDir, "results", "unbounded_certs"}]];
canonP[p_String] := First[Sort[Flatten[Table[strRotL[q, k], {q, {p, StringReplace[p, {"R" -> "L", "L" -> "R"}]}}, {k, 0, StringLength[p] - 1}]]]];
strRotL[s_, k_] := StringDrop[s, k] <> StringTake[s, k];
periods[a_] := With[{k = Keys[a["spectrum"]]}, If[Length[k] > 8, StringRiffle[ToString /@ Take[k, 4], ", "] <> ", ..., " <> StringRiffle[ToString /@ Take[k, -2], ", "] <> " (" <> ToString[Length[k]] <> " values)", StringRiffle[ToString /@ k, ", "]]];
specAgree[p_] := With[{w = Lookup[va, p, None]}, If[AssociationQ[w], TrueQ[w["agree"]], None]];   (* verify_all.wl: states, no escapes/timeouts, period spectrum *)
row[p_] := Module[{a = pm[p], v = Lookup[vc, p, None], ag = specAgree[p]},
   If[! (AssociationQ[v] && KeyExistsQ[v, "nclasses"]), Print["programs_md.wl: no class data (verify_classes.wxf) for ", p, "; run verify_classes.wl first"]; Exit[1]];
   If[ag === None, Print["programs_md.wl: no verify_all.wxf record for ", p]; Exit[1]];
   "| `" <> p <> "` | " <> ToString[a["n"]] <> " | " <> ToString[a["starts"]] <> " | " <> periods[a] <> " | " <> If[AssociationQ[v], ToString[v["nclasses"]], "-"] <> " | " <> Which[ag === True, "agree", ag === False, "DIFFER", True, "-"] <> " |"];
bounded = Sort[Keys[pm]];
boundedCanon = Union[canonP /@ bounded];
(* programs up to mirror / cyclic shift / powers *)
rootP[p_String] := Module[{n = StringLength[p]}, First[Select[Divisors[n], StringJoin[ConstantArray[StringTake[p, #], n/#]] === p &]] // (StringTake[p, #] &)];
boundedPow = Union[canonP[rootP[#]] & /@ bounded];
lines = {"# Complete lists of the programs of the theorems", "",
   "Generated by `notebook_src/programs_md.wl` from `results/proof_many.json`, `notebook_src/data/verify_classes.wxf`,",
   "`notebook_src/data/verify_extra.wxf`, `notebook_src/data/verify_all.wxf` and `results/unbounded_certs/certs_roots.json`",
   "(written by `collect_cert_roots.py`, which runs the three checkers on every certificate file) (2026-10-07).", "",
   "Programs are written without the cyclic star: `SSR` means (SSR)*.  A program is identified with its cyclic shifts",
   "and its mirror image (R <-> L); in the tables below the representative is the one used in the verification runs.", "",
   "## A. Bounded programs (Theorem 3 of the ASCAT paper / Theorem 4 of the full version)", "",
   "V(P, n) verified at level n with the Python pipeline (`prove2.py` / `prove_many.py`, numpy or CUDA) and re-verified with the",
   "Wolfram Language implementation (`notebook_src/verify_all.wl`, `verify_classes.wl`); \"classes\" is the number of congruence",
   "classes of swept sets (exact Z[zeta] canonical forms); \"agree\" means that the number of initial states, the absence of",
   "escapes and the period spectrum agree between the two implementations.", "",
   "Count: " <> ToString[Length[bounded]] <> " programs; " <> ToString[Length[boundedCanon]] <> " up to cyclic shifts and mirroring; " <> ToString[Length[boundedPow]] <> " up to cyclic shifts, mirroring and powers.", "",
   "| program | n | initial states | periods | classes | WL check (`verify_all.wl`: states, escapes, period spectrum) |", "|---|---:|---:|---|---:|---|"};
lines = Join[lines, row /@ bounded];
extraKeys = Sort[Complement[Union[Keys[ve], Keys[vc]], bounded]];
extraData[p_] := If[KeyExistsQ[ve, p], ve[p], vc[p]];
If[extraKeys =!= {},
  lines = Join[lines, {"", "## B. Further bounded programs (not counted in the theorems)", "",
     "Verified in the same way after the surveys (single exits k = 35, 40, 45, 50 and exit sequences that narrowly missed the",
     "candidate threshold of the survey); see `notebook_src/verify_extra.wl` and `notebook_src/py_extra.py`.", "",
     "| program | n | initial states | periods | escapes |", "|---|---:|---:|---|---:|"},
    Table[With[{v = extraData[p]}, "| `" <> First[StringSplit[p, "@"]] <> "` | " <> ToString[Lookup[v, "n", "-"]] <> " | " <> ToString[Lookup[v, "starts", "-"]] <> " | " <> If[KeyExistsQ[v, "spectrum"], periods[v], "-"] <> " | " <> ToString[Lookup[v, "escape", "-"]] <> " |"], {p, extraKeys}]]];
(* unbounded *)
typeName[{col_, s_}] := If[col == 1, "obtuse", "acute"] <> If[s > 0, " (+)", " (-)"];
rootRow[e_, r_] := "| `" <> e["prog"] <> "` | " <> ToString[e["B"]] <> " | " <> ToString[e["npass"]] <> " | " <> ToString[e["nports"]] <> " | " <> ToString[e["identities"]] <> " | " <> ToString[r["id"]] <> ": " <> typeName[r["type"]] <> ", " <> ToString[r["m0"]] <> " | " <> StringRiffle[ToString /@ Take[r["N"], UpTo[4]], ", "] <> " | N(m+2) = " <> ToString[r["a"]] <> " N(m) " <> If[r["b"] >= 0, "+ " <> ToString[r["b"]], "- " <> ToString[-r["b"]]] <> " | `" <> e["file"] <> "` | " <> If[TrueQ[e["valid"]], "valid", "INVALID"] <> If[TrueQ[e["indep_ok"]], ", indep. checker accepts", ""] <> If[TrueQ[e["o5_exact_ok"]], ", (V3) exact (surplus >= " <> ToString[NumberForm[e["o5_exact_surplus_lb"], {5, 3}]] <> ")", ""] <> " |";
urows = Flatten[Table[Table[rootRow[e, r], {r, e["roots"]}], {e, cr}]];
certFileNames = Select[certFiles, StringStartsQ[#, "cert_"] || StringStartsQ[#, "cert2_"] &];
If[Sort[cr[[All, "file"]]] =!= Sort[certFileNames], Print["programs_md.wl: certs_roots.json covers ", cr[[All, "file"]], " but the certificate files are ", certFileNames]; Exit[1]];
If[AnyTrue[cr, Length[#["roots"]] == 0 &], Print["programs_md.wl: certificate records without root families: ", Select[cr, Length[#["roots"]] == 0 &][[All, "file"]]]; Exit[1]];
If[Length[urows] =!= Total[Length[#["roots"]] & /@ cr], Print["programs_md.wl: row count mismatch"]; Exit[1]];
unboundedCanon = Union[canonP[#["prog"]] & /@ cr]; unboundedPow = Union[canonP[rootP[#["prog"]]] & /@ cr];
lines = Join[lines, {"", "## C. Unbounded programs (Theorem 5 of the ASCAT paper / Theorem 6 of the full version)", "",
   "Each line is one designated root of one certificate file (`results/unbounded_certs/`; data from `collect_cert_roots.py`).",
   "B is the base level, \"root\" the id, type and lowest level m0 of the self-reproducing pass family, N its lengths at the",
   "levels m0, m0+2, ..., and \"recurrence\" the exact recurrence proved by obligation O6 / condition (V5).  The last column",
   "gives the results of `verify_cert.py`, of the independently written `indep_check.py` and of the exact",
   "re-verification of the exit property (V3) by `verify_cert_exact.py`, with a rigorous lower bound of the margin surplus.",
   "`cert2_SSSR_1p_1.json` designates the positive obtuse root used in the paper; `cert_SSSR.json` is the same system with",
   "the negative obtuse root designated.  The programs are",
   ToString[Length[unboundedCanon]] <> " up to cyclic shifts and mirroring, and " <> ToString[Length[unboundedPow]] <> " up to cyclic shifts, mirroring and powers (the count used in the theorems).", "",
   "| program | B | pass families | port families | identities | root (id: type, m0) | N(m0), N(m0+2), ... | recurrence | certificate | checkers |",
   "|---|---:|---:|---:|---:|---|---|---|---|---|"}, urows];
lines = Join[lines, {""}];
Export[outFile, StringRiffle[lines, "\n"], "Text", CharacterEncoding -> "UTF-8"];
Print["PROGRAMS.md: bounded ", Length[bounded], " (", Length[boundedCanon], " / ", Length[boundedPow], "), extra ", Length[extraKeys], ", certificates ", Length[cr], " -> ", Length[unboundedCanon], " / ", Length[unboundedPow], " programs; WL agree: ", Count[specAgree /@ bounded, True], "/", Length[bounded]];
