(* programs_md.wl : write PROGRAMS.md, the complete lists of the programs of the theorems
   (bounded: results/proof_many.json + data/verify_classes.wxf + data/verify_extra.wxf;
    unbounded: results/unbounded_certs/summary.json and the certificate files)
   usage: run.wl programs_md.wl <outfile> *)
outFile = $args[[2]];
pm = Import[FileNameJoin[{$repoDir, "results", "proof_many.json"}], "RawJSON"];
vc = Import[FileNameJoin[{$dataDir, "verify_classes.wxf"}]];
ve = Quiet[Check[Import[FileNameJoin[{$dataDir, "verify_extra.wxf"}]], <||>]];
sm = Import[FileNameJoin[{$repoDir, "results", "unbounded_certs", "summary.json"}], "RawJSON"];
certFiles = FileNameTake /@ FileNames["*.json", FileNameJoin[{$repoDir, "results", "unbounded_certs"}]];
canonP[p_String] := First[Sort[Flatten[Table[strRotL[q, k], {q, {p, StringReplace[p, {"R" -> "L", "L" -> "R"}]}}, {k, 0, StringLength[p] - 1}]]]];
strRotL[s_, k_] := StringDrop[s, k] <> StringTake[s, k];
periods[a_] := With[{k = Keys[a["spectrum"]]}, If[Length[k] > 8, StringRiffle[ToString /@ Take[k, 4], ", "] <> ", ..., " <> StringRiffle[ToString /@ Take[k, -2], ", "] <> " (" <> ToString[Length[k]] <> " values)", StringRiffle[ToString /@ k, ", "]]];
row[p_] := Module[{a = pm[p], v = Lookup[vc, p, None]},
   "| `" <> p <> "` | " <> ToString[a["n"]] <> " | " <> ToString[a["starts"]] <> " | " <> periods[a] <> " | " <> If[AssociationQ[v], ToString[v["nclasses"]], "-"] <> " | " <> If[AssociationQ[v], If[v["escape"] == 0 && v["timeout"] == 0 && v["starts"] == a["starts"], "agree", "DIFFER"], "-"] <> " |"];
bounded = Sort[Keys[pm]];
boundedCanon = Union[canonP /@ bounded];
(* programs up to mirror / cyclic shift / powers *)
rootP[p_String] := Module[{n = StringLength[p]}, First[Select[Divisors[n], StringJoin[ConstantArray[StringTake[p, #], n/#]] === p &]] // (StringTake[p, #] &)];
boundedPow = Union[canonP[rootP[#]] & /@ bounded];
lines = {"# Complete lists of the programs of the theorems", "",
   "Generated by `notebook_src/programs_md.wl` from `results/proof_many.json`, `notebook_src/data/verify_classes.wxf`,",
   "`notebook_src/data/verify_extra.wxf` and `results/unbounded_certs/summary.json` (2026-10-07).", "",
   "Programs are written without the cyclic star: `SSR` means (SSR)*.  A program is identified with its cyclic shifts",
   "and its mirror image (R <-> L); in the tables below the representative is the one used in the verification runs.", "",
   "## A. Bounded programs (Theorem 3 of the ASCAT paper / Theorem 4 of the full version)", "",
   "V(P, n) verified at level n with the Python pipeline (`prove2.py` / `prove_many.py`, numpy or CUDA) and re-verified with the",
   "Wolfram Language implementation (`notebook_src/verify_all.wl`, `verify_classes.wl`); \"classes\" is the number of congruence",
   "classes of swept sets (exact Z[zeta] canonical forms); \"agree\" means that the number of initial states, the absence of",
   "escapes and the period spectrum agree between the two implementations.", "",
   "Count: " <> ToString[Length[bounded]] <> " programs; " <> ToString[Length[boundedCanon]] <> " up to cyclic shifts and mirroring; " <> ToString[Length[boundedPow]] <> " up to cyclic shifts, mirroring and powers.", "",
   "| program | n | initial states | periods | classes | WL check |", "|---|---:|---:|---|---:|---|"};
lines = Join[lines, row /@ bounded];
extraKeys = Sort[Complement[Union[Keys[ve], Keys[vc]], bounded]];
extraData[p_] := If[KeyExistsQ[ve, p], ve[p], vc[p]];
If[extraKeys =!= {},
  lines = Join[lines, {"", "## B. Further bounded programs (not counted in the theorems)", "",
     "Verified in the same way after the surveys (single exits k = 35, 40, 45, 50 and exit sequences that narrowly missed the",
     "candidate threshold of the survey); see `notebook_src/verify_extra.wl` and `notebook_src/py_extra.py`.", "",
     "| program | n | initial states | periods | escapes |", "|---|---:|---:|---|---:|"},
    Table[With[{v = extraData[p]}, "| `" <> p <> "` | " <> ToString[Lookup[v, "n", "-"]] <> " | " <> ToString[Lookup[v, "starts", "-"]] <> " | " <> If[KeyExistsQ[v, "spectrum"], periods[v], "-"] <> " | " <> ToString[Lookup[v, "escape", "-"]] <> " |"], {p, extraKeys}]]];
(* unbounded *)
typeName[{col_, s_}] := If[col == 1, "obtuse", "acute"] <> If[s > 0, " (+)", " (-)"];
urows = Table[Module[{p = e["prog"], file},
    file = SelectFirst[certFiles, StringContainsQ[#, "_" <> p <> "."] || StringContainsQ[#, "_" <> p <> "_"] &, "?"];
    "| `" <> p <> "` | " <> ToString[e["B"]] <> " | " <> ToString[e["npass"]] <> " | " <> ToString[e["nports"]] <> " | " <> ToString[e["identities"]] <> " | " <> typeName[e["root_type"]] <> ", " <> ToString[e["m0"]] <> " | " <> StringRiffle[ToString /@ e["N"], ", "] <> " | N(m+2) = " <> ToString[e["a"]] <> " N(m) " <> If[e["b"] >= 0, "+ " <> ToString[e["b"]], "- " <> ToString[-e["b"]]] <> " | `" <> file <> "` | " <> If[TrueQ[e["indep_ok"]], "both accept", "?"] <> " |"], {e, sm}];
unboundedCanon = Union[canonP[#["prog"]] & /@ sm]; unboundedPow = Union[canonP[rootP[#["prog"]]] & /@ sm];
lines = Join[lines, {"", "## C. Unbounded programs (Theorem 5 of the ASCAT paper / Theorem 6 of the full version)", "",
   "Each line is one certificate of a pass-substitution system (`results/unbounded_certs/`), accepted by both checkers",
   "`verify_cert.py` and `indep_check.py`.  B is the base level, \"root\" the type and lowest level m0 of the self-reproducing",
   "pass family, N its lengths at the levels m0, m0+2, ..., and the last column the exact recurrence proved by obligation O6.",
   "Several certificates may belong to the same program (e.g. roots of different type); the programs are",
   ToString[Length[unboundedCanon]] <> " up to cyclic shifts and mirroring, and " <> ToString[Length[unboundedPow]] <> " up to cyclic shifts, mirroring and powers (the count used in the theorems).", "",
   "| program | B | pass families | port families | identities | root (type, m0) | N(m0), N(m0+2), ... | recurrence | certificate | checkers |",
   "|---|---:|---:|---:|---:|---|---|---|---|---|"}, urows];
lines = Join[lines, {"", "The certificate of the positive obtuse root of (SSSR)* used in the paper (N = 202, 874, 3562, ...; N(m+2) = 4N(m) + 66) is `cert2_SSSR_1p_1.json`.", ""}];
Export[outFile, StringRiffle[lines, "\n"], "Text", CharacterEncoding -> "UTF-8"];
Print["PROGRAMS.md: bounded ", Length[bounded], " (", Length[boundedCanon], " / ", Length[boundedPow], "), extra ", Length[extraKeys], ", certificates ", Length[sm], " -> ", Length[unboundedCanon], " / ", Length[unboundedPow], " programs"];
